# Data paths
data_path: '../../preselection/crab_TTree_13TeV_mmmm_UL_Run2.root'
mc_path: '../../preselection/mmmm_mc_2018.root'

# Output paths
savepath_base: 'plots/optimization/test/'

# Analysis parameters
entry_stop: 100
columns:
  - Event
  - Run
  - LumiBlock
  - Mu_TriggerPath
  - FourL_VtxProb
  - FourL_pt
  - FourL_mass
  - B_Mu1_soft
  - B_Mu2_soft
  - B_Mu3_soft
  - B_Mu4_soft
  - B_Mu1_pt
  - B_Mu2_pt
  - B_Mu3_pt
  - B_Mu4_pt
  - B_Mu1_eta
  - B_Mu2_eta
  - B_Mu3_eta
  - B_Mu4_eta
  - B_Mu1_phi
  - B_Mu2_phi
  - B_Mu3_phi
  - B_Mu4_phi
  - B_J1_VtxProb
  - B_J2_VtxProb
  - B_J3_VtxProb
  - B_J4_VtxProb
  - B_J1_mass
  - B_J2_mass
  - B_J3_mass
  - B_J4_mass
  - B_J1_eta
  - B_J2_eta
  - B_J3_eta
  - B_J4_eta
  - B_J1_phi
  - B_J2_phi
  - B_J3_phi
  - B_J4_phi
  - B_J1_rapidity
  - B_J2_rapidity
  - B_J3_rapidity
  - B_J4_rapidity




# Cut parameters
cut_parameters:
  elePt_low: [5]
  elePt_high: [5]
  eleEta: [2.5]
  ymass_upper: [10]

# Output file
output_file: 'FOM_results.csv'